from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from geopy.geocoders import Nominatim
from event import Event
from mysql.connector import Error

class Ui_AddEventDialog(object):
    def setupUi(self, AddEventDialog):
        AddEventDialog.setObjectName("AddEventDialog")
        AddEventDialog.setFixedSize(340, 400)
        AddEventDialog.setWindowTitle("Добавление события")
        self.AddEventDialog = AddEventDialog

        self.addressFrame = QtWidgets.QLabel(AddEventDialog)
        self.addressFrame.setGeometry(QtCore.QRect(18, 248, 304, 94))
        self.addressFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.addressFrame.setObjectName("addressFrame")

        self.eventNameLabel = QtWidgets.QLabel(AddEventDialog)
        self.eventNameLabel.setGeometry(QtCore.QRect(20, 10, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.eventNameLabel.setFont(font)
        self.eventNameLabel.setObjectName("eventNameLabel")
        self.eventNameLabel.setText("Название события:")

        self.eventNameLine = QtWidgets.QLineEdit(AddEventDialog)
        self.eventNameLine.setGeometry(QtCore.QRect(20, 40, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.eventNameLine.setFont(font)
        self.eventNameLine.setObjectName("eventNameLine")

        self.descriptionLabel = QtWidgets.QLabel(AddEventDialog)
        self.descriptionLabel.setGeometry(QtCore.QRect(20, 80, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.descriptionLabel.setFont(font)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.descriptionLabel.setText("Описание события:")

        self.descriptionLine = QtWidgets.QLineEdit(AddEventDialog)
        self.descriptionLine.setGeometry(QtCore.QRect(20, 110, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.descriptionLine.setFont(font)
        self.descriptionLine.setObjectName("descriptionLine")

        self.dateTimeLabel = QtWidgets.QLabel(AddEventDialog)
        self.dateTimeLabel.setGeometry(QtCore.QRect(20, 150, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dateTimeLabel.setFont(font)
        self.dateTimeLabel.setObjectName("dateTimeLabel")
        self.dateTimeLabel.setText("Дата и время:")

        self.dateTimeEdit = QtWidgets.QDateTimeEdit(AddEventDialog)
        self.dateTimeEdit.setGeometry(QtCore.QRect(20, 180, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setObjectName("dateTimeEdit")

        self.cityLine = QtWidgets.QLineEdit(AddEventDialog)
        self.cityLine.setGeometry(QtCore.QRect(120, 250, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cityLine.setFont(font)
        self.cityLine.setObjectName("cityLine")

        self.streetLine = QtWidgets.QLineEdit(AddEventDialog)
        self.streetLine.setGeometry(QtCore.QRect(120, 280, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.streetLine.setFont(font)
        self.streetLine.setObjectName("streetLine")

        self.houseLine = QtWidgets.QLineEdit(AddEventDialog)
        self.houseLine.setGeometry(QtCore.QRect(120, 310, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.houseLine.setFont(font)
        self.houseLine.setObjectName("houseLine")

        self.addressLabel = QtWidgets.QLabel(AddEventDialog)
        self.addressLabel.setGeometry(QtCore.QRect(20, 220, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.addressLabel.setFont(font)
        self.addressLabel.setObjectName("addressLabel")
        self.addressLabel.setText("Адрес события:")

        self.cityLabel = QtWidgets.QLabel(AddEventDialog)
        self.cityLabel.setGeometry(QtCore.QRect(20, 250, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cityLabel.setFont(font)
        self.cityLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cityLabel.setObjectName("cityLabel")
        self.cityLabel.setText("Город:")

        self.streetLabel = QtWidgets.QLabel(AddEventDialog)
        self.streetLabel.setGeometry(QtCore.QRect(20, 280, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.streetLabel.setFont(font)
        self.streetLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.streetLabel.setObjectName("streetLabel")
        self.streetLabel.setText("Улица:")

        self.houseLabel = QtWidgets.QLabel(AddEventDialog)
        self.houseLabel.setGeometry(QtCore.QRect(20, 310, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.houseLabel.setFont(font)
        self.houseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.houseLabel.setObjectName("houseLabel")
        self.houseLabel.setText("Дом:")

        self.addButton = QtWidgets.QPushButton(AddEventDialog)
        self.addButton.setGeometry(QtCore.QRect(30, 355, 130, 35))
        self.addButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.addButton.setText("Добавить")
        self.addButton.clicked.connect(self.onAddButtonClicked)

        self.cancelButton = QtWidgets.QPushButton(AddEventDialog)
        self.cancelButton.setGeometry(QtCore.QRect(180, 355, 130, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.cancelButton.setText("Отмена")
        self.cancelButton.clicked.connect(AddEventDialog.close)

    def onAddButtonClicked(self):
        try:
            address = ",".join(filter(None, [self.cityLine.text(), self.streetLine.text(), self.houseLine.text()]))
            geolocator = Nominatim(user_agent="alla123425")
            location = geolocator.geocode(address)

            if location:
                self.currentEvent = Event(0, self.eventNameLine.text(), self.descriptionLine.text(), "я", self.dateTimeEdit.dateTime().toString("yyyy-MM-dd HH:mm:ss"), self.cityLine.text(), self.streetLine.text(), self.houseLine.text(), location.latitude, location.longitude)
                self.AddEventDialog.accept()
            else:
                raise ValueError("Адрес не найден")
        except ValueError as e:
            QMessageBox.warning(self.AddEventDialog, "Неверный адрес", e, QMessageBox.Ok)
        except Error as e:
            QMessageBox.warning(self.AddEventDialog, "Ошибка при соединении с БД", e, QMessageBox.Ok)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddEventDialog = QtWidgets.QDialog()
    ui = Ui_AddEventDialog()
    ui.setupUi(AddEventDialog)
    AddEventDialog.show()
    sys.exit(app.exec_())
